### ISSUE TITLE
🚀| Warn when targets in the same environment have the same name

### ISSUE THREAD

**Issue by bessonm** [chutney-testing/chutney-kotlin-dsl#38]
Since the target name is used as an identifier, having targets with the same name in the same environment is not recommended.
We could warn users and even prevent execution, since it could lead to unexpected system state.

Solution : 
In [Environments.kt](https://github.com/chutney-testing/chutney-kotlin-dsl/blob/4ae13611e431b7888bba2c040342ad33076405a7/example/src/main/kotlin/com/chutneytesting/Environments.kt) constructor, raise an exception if there are targets with same name

**Comment by nbrouand** [comment]
Add the logic in Environments construtor
