### ISSUE TITLE
🚀 | src/resources/chutney/in_progress folder must be created automatically if not exist

### ISSUE THREAD

**Issue by KarimGl** [chutney-testing/chutney-kotlin-dsl#68]
## Describe your use case

- create scenario
- call synchronize method without setting path and pathCreated parameters
- execution is KO: src/resources/chutney/in_progress not found

## Describe the solution you'd like
folder containing created json scenarios must e created automatically if not exist by synchronize method

**Comment by nbrouand** [comment]
Fix in #75
